services:
    client-vite:
        image: client-vite:dev
        build:
            context: client-vite/
        init: true
        volumes:
            - type: bind
              source: client-vite/
              target: /usr/src/app/
            - type: volume
              target: /usr/src/app/node_modules
        networks:
            - frontend
        ports:
            - 8080:5173
    api-django:
        image: api-django:dev
        build:
            context: api-django/
        init: true
        networks:
            - frontend
            - backend
        ports:
            - 8000:8000
networks:
    frontend:
    backend:
